# Generated by Django 2.1.7 on 2019-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an Image', max_length=16384, null=True, upload_to='expense_image/', verbose_name='Image')),
                ('cost', models.PositiveSmallIntegerField(help_text='Enter the Amount Expended', verbose_name='Expenditure Cost')),
                ('description', models.TextField(help_text='Enter the Description for the type of expense', verbose_name='Description')),
            ],
        ),
    ]
