# Generated by Django 2.1.7 on 2019-03-19 14:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 14, 24, 44, 688523, tzinfo=utc), verbose_name='Bill Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default=datetime.datetime(2019, 3, 19, 14, 25, 6, 67752, tzinfo=utc), help_text='A brief title of the expense', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, help_text='Choose the User to whom this expense belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
