# Generated by Django 2.1.7 on 2019-03-19 15:52

from django.db import migrations, models
import django.utils.timezone
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20190319_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Billing Time'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Bill Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', to='tracker.Tagulous_Expense_tags'),
        ),
    ]
