# Generated by Django 2.1.7 on 2019-03-21 11:12

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190319_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-bill_date']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the Description for the type of expense', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', to='tracker.Tagulous_Expense_tags'),
        ),
    ]
